# rubocop todo
#

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/integration/mysql/serverspec/mysql_spec.rb'

Style/MultilineTernaryOperator:
  Exclude:
    - 'libraries/provider_database_postgresql.rb'
